project:
  type: website

website:
  title: "simple_quarto_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.ipynb
        text: About
      - href: ./slides/slides.ipynb
        text: Presentation

format:
  html:
    theme: cosmo
    toc: true
    execute: true



